version: "3.9"

services:

  db:
    image: postgres:13
    container_name: policy_form_postgres_db
    env_file: 
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always
  
    networks:
      - policy_network

  streamlit:
    build:
      context: .
      dockerfile: dockerfile

    container_name: streamlit_backend
    env_file: 
      - .env
    ports:
      - "8501:8501"

    volumes:
      - ./:/policy-backend
    depends_on:
      - db
    networks:
      - policy_network

volumes:
  postgres_data:

networks:
  policy_network:
